### ISSUE TITLE
Completely freezes installation on symlinked node_modules directory

### ISSUE THREAD

**Issue by zanona** [kevva/bin-wrapper#35]
As requested at [imagemin/gifsicle-bin#47](https://github.com/imagemin/gifsicle-bin/issues/47#issuecomment-72044375) I am opening an issue here.

Steps to reproduce: 

- OSX 10.10.1
- node: v0.10.33
- npm: 2.1.11

```bash
cd ~/my-app
mkdir ~/node_modules
ln -s ~/node_modules ~/my-app
npm install gifsicle
```

Hangs installation forever with:
```
> gifsicle@2.0.1 postinstall /Users/zanona/my-app/node_modules/gifsicle
> node lib/install.js
```

**Comment by kevva** [comment]
https://github.com/kevva/bin-wrapper/blob/master/index.js#L199-L221

**Comment by karlvr** [comment]
I'm investigating this in reference to imagemin/imagemin#68. I have narrowed it down to the files array in the BinWrapper.prototype.symlink function being empty in the successful case and containing a file in the failure case. It continues...

**Comment by karlvr** [comment]
Aha, information. In the imagemin/imagemin#68 case the `which.sync` call is failing due to:
```
Error: not found: npm
```

Perhaps the error shouldn't be ignored here? Or perhaps it shouldn't return `true`? I'm investigating why `npm` can't be found, in the imagemin/imagemin#68 case - maybe there's a similar hidden error in this bug's case?

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/bin-wrapper/commit/8bf6687b935bc7b03acb9b762f963807c8cf024c (somewhat).

**Comment by zanona** [comment]
brilliant! thanks a bunch @kevva!
